Use older travis image
This fixes a permission issue, unrelated to our build:
OSError: [Errno 13] Permission denied: '/usr/local/bin/easy_install'

(cherry picked from commit a297f6bf7a3a0a64754b8d39fae11a9e0c26c370)