Add missing npm module
```
module.js:440
    throw err;
    ^
Error: Cannot find module 'buffer-shims'
    at Function.Module._resolveFilename (module.js:438:15)
    at Function.Module._load (module.js:386:25)
    ...
```

https://travis-ci.org/cyverse/troposphere/jobs/185529236