Degrading iplant-auth until fix
The upgrade in commit 04e849879ee9a938155ca0c4a815a6363647dda9 of
django-iplant-auth has introduced as regression with the following
error message:

```
Exception Type: TypeError at /tropo-api/users
Exception Value: get_profile() got an unexpected keyword argument 'key'
```

This appears to come from a change on Jan. 11 to iplant-auth:

https://github.com/iPlantCollaborativeOpenSource/django-iplant-auth/commit/7e74e6c38ee821841bbcd239e0ff65ea1fb4a319

The CAS client library has not change since August 2015, so it still
does *not* accept `key` as a keyword argument.

This regression was fixed before in November 2015:

https://github.com/iPlantCollaborativeOpenSource/django-iplant-auth/commit/ebd54a3e343a602a2f7cc70ed7f367e764ed73b5