Add missing npm module nodejs, >5.1
Several TravisCI builds for nodejs (5.1, 6.1) are failing with:

```
module.js:440
    throw err;
    ^
Error: Cannot find module 'process-nextick-args'
```
src: https://travis-ci.org/cyverse/troposphere/jobs/185515332

Attempting to add `process-nextick-args` to resolve.